@url = http://localhost:8080/api/user

POST {{url}}
Content-Type: application/json

{
  "username": "test1",
  "password": "password",
  "email": "test1@gmail.com",
  "firstName": "",
  "lastName": "Deen",
  "bio": "Here is a BIo skdfjlskdjflskdjflskjdlfksjdlfksjdlfkjsdlfkjsldkfjs",
  "state": "AZ",
  "city": "Tucson",
  "zipCode": "85715",
  "profileImgUrl" : "https://bit.ly/naruto-sage",
  "instrument": "Guitar"
}

###

POST {{url}}/authenticate
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "password"
}

###
GET {{url}}/profile/test1

###

PUT {{url}}/1
Content-Type: application/json

{
  "id": 1,
  "username": "change",
  "password": "password",
  "email": "test1@gmail.com",
  "firstName": "",
  "lastName": "Deen",
  "bio": "Here is a BIo skdfjlskdjflskdjflskjdlfksjdlfksjdlfkjsdlfkjsldkfjs",
  "state": "AZ",
  "city": "Tucson",
  "zipCode": "85715",
  "profileImgUrl" : "https://bit.ly/naruto-sage",
  "instrument": "Guitar"
}

###
GET {{url}}/test1@gmail.com

###
DELETE {{url}}/songs/2